# Generated by Django 5.2.7 on 2025-10-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SkillConnect", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_img",
            field=models.ImageField(upload_to="uploads/images/"),
        ),
    ]
