# Generated by Django 5.2.7 on 2025-11-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("SkillConnect", "0002_alter_customuser_bio_alter_customuser_profile_img"),
        ("work", "0002_skills_userskill_description_alter_userskill_skill_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Skills",
        ),
    ]
