# Generated by Django 5.2.7 on 2025-11-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="userskill",
            name="description",
            field=models.CharField(default="Description"),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="skill",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_skills",
                to="work.skills",
            ),
        ),
        migrations.AlterField(
            model_name="workoffers",
            name="skills_required",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="work.skills"
            ),
        ),
    ]
