# Generated by Django 5.2.7 on 2025-11-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0002_skills_userskill_description_alter_userskill_skill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userskill",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="proficiency_level",
            field=models.IntegerField(
                choices=[(1, "beginner"), (2, "intermediate"), (3, "pro")], default=1
            ),
        ),
    ]
