# Generated by Django 5.2.7 on 2025-11-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0003_alter_userskill_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workoffers",
            name="price",
        ),
        migrations.RemoveField(
            model_name="workoffers",
            name="skills_required",
        ),
    ]
